### ISSUE TITLE
Print bed size?

### ISSUE THREAD

**Issue by cscott** [Chrismettal/EleLab_v2#1]
Nice project!  Would be helpful if you mentioned up top in the README what size print bed is required and/or some options for printing on smaller printers.

**Comment by Chrismettal** [comment]
Good idea. I just updated the README with some general printer considerations. 
In the future i might go and split the very large print files, namely the ATX and SFX supply modules, as they approach the boundary box of Prusa machines in the X direction, which i alway count as the standard median printer.
