### ISSUE TITLE
Gitlab link is to wrong repo. 

### ISSUE THREAD

**Issue by ScaredyCat** [Chrismettal/EleLab_v2#10]
The gitlab link (linked from printables)

![gitlabde](https://github.com/Chrismettal/EleLab_v2/assets/168872/b16930c4-92f2-42c7-ba35-d20821c95b9f)

 links to the wrong github repo.

![gitlabdd](https://github.com/Chrismettal/EleLab_v2/assets/168872/0411b552-ca10-4210-9447-b07f7704ff31)

and should link to 

https://github.com/Chrismettal/EleLab_v2

**Comment by Chrismettal** [comment]
Good catch, thank you! Updated both occurences (Linking from Printables here directly, as well as correctly linking from GitLab to Github)
Which was fun.. Thanks Prusa for not having an API to mass update descriptions.
