### ISSUE TITLE
Raspbery pi module?

### ISSUE THREAD

**Issue by cscott** [Chrismettal/EleLab_v2#3]
It might be nice to add a Raspberry Pi module, with a small display and maybe even a trackpad, so you could do basic "look up on the internet", "I need a calculator", or "toggle this GPIO" tasks.

**Comment by Chrismettal** [comment]
Yeah a display module is certainly in the works. I don't think i'll couple Rpi and display in the same module but rather have them as two modules next to each other so each of them can be used on its own. But yeah, gonna do that eventually.

**Comment by Chrismettal** [comment]
RPi as well as display module now finished. That took a while didn't it?
