### ISSUE TITLE
PCB files?

### ISSUE THREAD

**Issue by Ajb2k3** [Chrismettal/EleLab_v2#4]
What program did you use to make the PCBs?
I would like to import into easy eda but just get file error trying to import file.

**Comment by Chrismettal** [comment]
I made the PCBs in KiCAD. EasyEDA is a PCB designer right? I don't know the import functions of EasyEDA, but i just recloned and retried to upload the gerbers for all the PCBs to jlcpcb for example and the gerbers all worked. Are you trying to edit the PCB designs? If so you might be better off just downloading KiCAD (open source btw) than trying to import it into another designer. 
Mind sharing what you are trying to edit?

**Comment by Ajb2k3** [comment]
I use Fritzing or easyeda for panel pcbs.
I downloaded the zip but osx opens the zip automatically and if I try to recompress and import I get file read error (Not edited the files yet!)
I've got KiCad on download so will see.
I'm working on some designs for a system powered by a solar panel but I need to add a booster to get the 12v up to 24v for some devices. I also need to add a fuseboard module and modules for powering a mini 3d printer and a mini laser engraver.

**Comment by Chrismettal** [comment]
I did not put any zips into the repo itself, just the raw gerber files in a single "Gerber" folder per PCB. Do you clone the whole repo and zip the "Gerber" folder yourself or are you downloading individual files?

I like your ideas for new modules! Especially the fuseboard. I opted for a PowerFeed PCB with front panel fuses for better access as i did not want to populate too many components on the PCB itself for rebuilding purposes. But please share your edits. Would be happy to adopt working new designs into this repo.

**Comment by Ajb2k3** [comment]
Will be a pleasure to share my designs into your hub.

Got kicad and rearchived from kicad and its working again.
The fuseboard is just to make a clean version for automotive fuse holders.
I'm going to use the Powerfeed as a mains "Backup" supply

**Comment by Chrismettal** [comment]
Great! I'm looking forward to your design.

**Comment by Ajb2k3** [comment]
I was trying to import into easyeda as I use easy Eda and fritzing. I am
trying to design a pCD board to connect to my solar setup but using a boost
converter to get 24v. If I make a working pcb I would be happy to share for
you to add to the project. I also need a corner pcb.
