### ISSUE TITLE
Multimeter module?

### ISSUE THREAD

**Issue by adelkheniche** [Chrismettal/EleLab_v2#5]
A workbench multimeter can be helpful too it Will be great to have it integrate in a module less cable everywhere when we are using it

**Comment by Chrismettal** [comment]
That is a nice idea. I struggle to find suitable multimeter modules though. I don't think it would be helpful to just have these little voltage displays that you put in your car to monitor your battery. Do you have a nice module in mind?

**Comment by Chrismettal** [comment]
Can't find a good multimeter module that would make sense in this. Only cheap voltage meters are available which i don't find helpful at all.
