### ISSUE TITLE
24V in + and gnd linked together.

### ISSUE THREAD

**Issue by Ajb2k3** [Chrismettal/EleLab_v2#6]
just noticed on the powerfeed board that +24v in and gnd 24v are linked together.
I recommend these pins are seperated to prevent confusion.

Sorry been too busy to work on it.

**Comment by Chrismettal** [comment]
Can you explain what exactly is your problem with this?

There are two 24 V terminals labeled as such and there is no designated "24 V gnd". I designed this so i can put 24 V into the bus but also have a terminal where i can connect the DC-DC converters to for the other voltages.

If you are inputting 24 V , you usually won't be populating the ATX connectors, so then you would use the left side of the ATX 8pin for ground as labeled.
 
![grafik](https://user-images.githubusercontent.com/39636046/91644720-01aa5200-ea3f-11ea-9e3b-aae3ab60bb3c.png)
